### ISSUE TITLE
Cli does not work

### ISSUE THREAD

**Issue by mostafafarzaneh** [cisco-ce/macrofy#1]
I get this error:
TypeError: build is not a function

**Comment by wewiley** [comment]
I cannot seem to get this to work at all.  See output below:

C:\Users\WesWiley\Scripts\Javascript\tplink>npx macrofy node_modules/tplink-smartplug-node/index.js index.js
C:\Users\WesWiley\node_modules\rollup\dist\shared\rollup.js:198
        base = Object.assign(new Error(base.message), base);
                             ^

Error: Could not resolve entry module (node_modules/tplink-smartplug-node/index.js).
    at error (C:\Users\WesWiley\node_modules\rollup\dist\shared\rollup.js:198:30)
    at ModuleLoader.loadEntryModule (C:\Users\WesWiley\node_modules\rollup\dist\shared\rollup.js:22306:20)
    at async Promise.all (index 0) {
  code: 'UNRESOLVED_ENTRY'
}

Node.js v20.11.1
